server:
  port: 8083

eureka:
  client:
    service-url:
      default-zone : http://localhost:8761


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: postgres
    password: divel213
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: CUSTOMER-SERVICE